services:
  transform-rpc:
    build:
      context: .
      dockerfile: services/rpc/transform/Dockerfile
      target: debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "8081:8081"
      - "2346:2345"

  shorturl-api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
      target: debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:8080"
      - "2345:2345"
